### ISSUE TITLE
Great library but Im getting issue with mp4 (no audio track)

### ISSUE THREAD

**Issue by nailbuster** [FactoryXCode/MfPack#12]
Really nice library.  and ive tested it for a bit and seems to work really well.

BUT,  I have one issue that not sure if its library or windows driver/framework issue.

Using (TMfPlayer).  If I quickly switch between an mp4 with an audio track...to an mp4 that has no audio track.  It works like 50% of time, the other 50% of time i get a freeze/hang and testapp crashes/closes out.  I can make crash happen always in a test app.  If i quickly switch between two mp4 files with both having audio tracks...works 100%.  (if I destroy and re-create player between mp4s then that works 100% ok, but its too slow recreating player for each switching of files for my needs) 

Tried for a bit playing with all sorts of stuff but couldn't stop the crashes.  My project uses a mix of mp4s with and without audio (btw:  project works fine with VLC player 100% but would like to try a diff media library if possible).

any ideas?  thanks...

**Comment by FactoryXCode** [comment]
Hello,

Your issue is very likely a threading error.
As you should know, the Media Foundation platform typically uses asynchronous methods based on events.
So, your app needs to wait for the appropriate event to continue with a next process. 
Use threadprotection mechanisms, like the TRTLCriticalSection (Windows unit) or TCriticalSection class (SyncObjs unit).
I would advise you to use a debugger like [MadExcept](http://madshi.net)

Greetings, Tony.
