### ISSUE TITLE
MfUtils function CopyTRectToLPRect frees returned pointer before exit

### ISSUE THREAD

**Issue by ariel2048** [FactoryXCode/MfPack#16]
I am evaluating MfPlayer I example and noted that if I add FastMM4 or FastMM5, video doesn't show.
Using FastMM5 it throws an exception in MfPlayer class, in the line:

hr := m_pVideoDisplay.SetVideoPosition(nil, rcd);

hr value here is $80070057: ERROR_INVALID_PARAMETER

The problem is that function CopyTRectToLPRect frees the memory of the returned pointer before exit, and FastMM reveals that situation.

Function CopyPRectToTRect seems to have some memory problems also. The memory allocated is leaked and the memory of parameter rs is freed. 

It's not right to free the memory that will be accessed afterwards; its a source of access violations and other memory problems.

**Comment by FactoryXCode** [comment]
Thanks.
We have some bad experiences with fastmm, so we never use it. (Deleaker Profiler, MadExcept or mftrace are the tools we use)
The issue is not related to the sample, but the helperunit that holds the conversions. 
The  function SetVideoPosition is working wel, function  CopyTRectToLPRect did not, so it has been changed in mfutils.pas. It should now works as expected.
