### ISSUE TITLE
Wrong function signature of PENABLECALLBACK and EventWrite in MfPack.Evntprov.pas

### ISSUE THREAD

**Issue by MBulli** [FactoryXCode/MfPack#5]
While using the MfPack.Evntprov unit to write ETW events I found two invalid function signatures.

To make my program run without compile or runtime errors I had to change the signature of EventWrite:

```pas
  function EventWrite(RegHandle: REGHANDLE;
                      const EventDescriptor: EVENT_DESCRIPTOR;
                      UserDataCount: ULONG;
                      UserData: PEVENT_DATA_DESCRIPTOR { now a pointer } ): ULONG; stdcall;
```
UserData needs to be a pointer because its an array (EVENT_DATA_DESCRIPTOR -> **P**EVENT_DATA_DESCRIPTOR).

Regarding the PENABLECALLBACK callback I had to change the signature from a function returning a ULONG to a procedure:
```pas
  PENABLECALLBACK = procedure(const SourceId: TGUID;
                             IsEnabled: ULONG;
                             Level: UCHAR; //UCHAR
                             MatchAnyKeyword: ULONGLONG;
                             MatchAllKeyword: ULONGLONG;
                             FilterData: PEVENT_FILTER_DESCRIPTOR;
                             CallbackContext: PVOID); stdcall;
```
Also, I don't know why the Level parameter is an INT instead of an UCHAR (see https://docs.microsoft.com/en-us/windows/win32/api/evntprov/nc-evntprov-penablecallback). However, it seems to make no difference ...

**Comment by FactoryXCode** [comment]
Hi, thank you for the input.
About the pointer to an array you are right. I think we skipped this issue for investigation (have to look in our todo list).
But now I'm (Tony) here, I could repair and commits it directly.
About the UCHAR: Thats a byte value, so as long the int will not exceed 255 there is nothing going on. However when I looked in to the maintenance database it was changed because the API declared it as int.  I checked it , and the api says: No. It's a Byte value, So there you go. I changed that as well: all fixed now and comitted. Thanks a lot!

**Comment by FactoryXCode** [comment]
Thank you!
I (Tony) looked it up in the history database, but no clue why it was changed to Int. However UCHAR is a byte value so, if it doesn't exceed 255 Int will do as well. But that is not how it should be.
I fixed this and uploaded a commit.
